#!/usr/bin/env python3
"""Write a figure's pixel grids (dark + light mode) to a Magnus JS module.

  python3 art/export.py heron_sun_vignette src/ui/art/heronSun.js HERON_SUN

Each row is a string, one character per pixel; LEGEND maps characters to
tone names (the theme's named colors), '.' is transparent.
"""
import json, sys
import figures
from pix import ANSI

name, out_path, const = sys.argv[1:4]
tones = list(ANSI)
code = {t: 'abcdefghijklmnop'[i] for i, t in enumerate(tones)}
fig = figures.ALL_FIGURES[name]()
def rows(c):
    return [''.join(code[t] if t else '.' for t in row) for row in c.g]
data = {'width': fig.w, 'height': fig.h, 'dark': rows(fig), 'light': rows(fig.for_light())}
legend = {v: k for k, v in code.items()}
with open(out_path, 'w') as f:
    f.write(f"// Generated by art/export.py from art/figures.py:{name}. Don't edit by hand.\n")
    f.write(f"export const {const}_LEGEND = {json.dumps(legend)};\n")
    f.write(f"export const {const} = {json.dumps(data, indent=1)};\n")
print(f'wrote {out_path}: {fig.w}x{fig.h} px')
