#!/usr/bin/env python3
"""Write the Home art (dark + light pixel grids, with animation frames) to a Magnus JS module.

  python3 art/export.py          → src/ui/art/heronSun.js

Each row is a string, one character per pixel; LEGEND maps characters to tone
names (the theme's named colors), '.' is transparent. TIMELINE lists
[frame, milliseconds] steps that loop.
"""
import json, os
import figures
from pix import ANSI

OUT = os.path.join(os.path.dirname(__file__), '..', 'src', 'ui', 'art', 'heronSun.js')
fig = figures.ALL_FIGURES['heron_sun_vignette']
# frames: (glide offset, wing, shimmer)
FRAMES = [(0, 'up', 0), (0, 'up', 1), (1, 'up', 0), (1, 'up', 1), (0, 'mid', 0), (1, 'mid', 1)]
# a slow glide (about 3 s up and down) with the shimmer every step, and one wing beat per loop
TIMELINE = [[0, 600], [1, 600], [0, 600], [3, 600], [2, 600], [3, 600], [2, 600], [1, 600],
            [4, 160], [0, 220], [4, 160], [1, 600]]
code = {t: 'abcdefghijklmnop'[i] for i, t in enumerate(ANSI)}
rows = lambda c: [''.join(code[t] if t else '.' for t in row) for row in c.g]
frames = [fig(dy, wing, sh) for dy, wing, sh in FRAMES]
data = {'width': frames[0].w, 'height': frames[0].h,
        'dark': [rows(f) for f in frames], 'light': [rows(f.for_light()) for f in frames], 'timeline': TIMELINE}
with open(OUT, 'w') as f:
    f.write("// Generated by art/export.py from art/figures.py:heron_sun_vignette. Don't edit by hand.\n")
    f.write(f"export const HERON_SUN_LEGEND = {json.dumps({v: k for k, v in code.items()})};\n")
    f.write(f"export const HERON_SUN = {json.dumps(data)};\n")
print(f'wrote {os.path.normpath(OUT)}: {len(frames)} frames, {data["width"]}x{data["height"]} px')
