#!/usr/bin/env node
// Generate the Magnus Web app's theme CSS from the terminal themes:
//   node terminal-theme/tools/build-web.mjs <magnus-web-repo-dir>
//
// Reads each family's finished Ghostty theme files (so the web app gets
// exactly the same, contrast-tuned colors as the terminal) and writes:
//   <dir>/themes.css       CSS variables per family and light/dark mode
//   <dir>/js/palettes.js   the list of families, for the theme picker
// and then runs <dir>/scripts/generate-icon.py to redraw the per-theme icons.
//
// The web app styles everything through the CSS variables in its style.css;
// these blocks override them via html[data-palette="…"][data-theme="…"].
// Card, sidebar and hover shades are chosen so every text color stays
// >= 4.5:1 on them, and button text is whichever of the page background or
// white reads best on the accent/danger color. A contrast report is printed.
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { FAMILIES, familyColors, contrast } from './colors.mjs';
const outDir = process.argv[2];
if (!outDir) {
  console.error('usage: build-web.mjs <magnus-web-repo-dir>');
  process.exit(1);
}

// ---------- build ----------
const blocks = [];
const report = [];
for (const fam of FAMILIES) {
  for (const mode of ['light', 'dark']) {
    const { g, r, dark, texts, surface, hover, subtleTo, subtleAlpha, subtle, accentTint, sidebar, border, accentHover, dangerHover, onAccent, onDanger } = familyColors(fam, mode);

    const vars = {
      '--bg': g.bg,
      '--surface': surface,
      '--sidebar-bg': sidebar,
      '--surface-subtle': subtleTo === '#ffffff' ? `rgba(255,255,255,${subtleAlpha})` : `rgba(0,0,0,${subtleAlpha})`,
      '--accent-tint': accentTint,
      '--border': border,
      '--text': g.fg,
      '--text-muted': r.muted,
      '--accent': r.accent,
      '--accent-hover': accentHover,
      '--on-accent': onAccent,
      '--danger': r.error,
      '--danger-hover': dangerHover,
      '--on-danger': onDanger,
      '--overdue': r.error,
      '--soon': r.warning,
      '--success': r.success,
      '--chip-bg': dark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.04)',
      '--hover-bg': hover,
      '--overlay-bg': dark ? 'rgba(0,0,0,0.5)' : 'rgba(0,0,0,0.25)',
      '--modal-shadow': dark ? '0 12px 40px rgba(0,0,0,0.5)' : '0 12px 40px rgba(0,0,0,0.18)',
      '--toast-shadow': dark ? '0 8px 24px rgba(0,0,0,0.4)' : '0 8px 24px rgba(0,0,0,0.14)',
      '--theme-color': g.bg,
    };
    const selector = dark ? `html[data-palette="${fam.key}"][data-theme="dark"]` : `html[data-palette="${fam.key}"]`;
    blocks.push(`/* ${fam.label} — ${mode} */\n${selector} {\n${Object.entries(vars).map(([k, v]) => `  ${k}: ${v};`).join('\n')}\n}`);

    const worst = Math.min(...texts.flatMap((c) => [g.bg, surface, hover, sidebar, subtle, accentTint].map((b) => contrast(c, b))));
    report.push(
      `${fam.label.padEnd(12)} ${mode.padEnd(5)} text/muted/accent/danger/soon/success on bg, cards, sidebar, hover, columns, tints >= ${worst.toFixed(2)}:1; ` +
        `button text on accent ${contrast(onAccent, r.accent).toFixed(1)}:1, on danger ${contrast(onDanger, r.error).toFixed(1)}:1`
    );
  }
}

const header = `/* Generated by the Magnus repo: terminal-theme/tools/build-web.mjs.
 * Do not edit by hand — change the terminal themes there and regenerate.
 * Each theme sets the same CSS variables style.css uses. Light values apply
 * via html[data-palette="…"]; dark via html[data-palette="…"][data-theme="dark"].
 * js/theme-boot.js sets both attributes. */\n\n`;
fs.writeFileSync(path.join(outDir, 'themes.css'), header + blocks.join('\n\n') + '\n');
fs.writeFileSync(
  path.join(outDir, 'js', 'palettes.js'),
  `// Generated by the Magnus repo: terminal-theme/tools/build-web.mjs. Do not edit by hand.\n` +
    `export const PALETTES = ${JSON.stringify(FAMILIES.map(({ key, label }) => ({ key, label })), null, 2)};\n` +
    `export const DEFAULT_PALETTE = 'hearth';\n`
);
console.log(report.join('\n'));
console.log(`Wrote ${path.join(outDir, 'themes.css')} and ${path.join(outDir, 'js', 'palettes.js')}`);

// The web app's per-theme icons are drawn from themes.css by its own script.
const iconScript = path.join(outDir, 'scripts', 'generate-icon.py');
if (fs.existsSync(iconScript)) {
  execFileSync('python3', [iconScript], { stdio: 'inherit' });
}
