#!/usr/bin/env node
// Build a terminal-theme family from terminal-theme/<family>/palette.json:
//   node terminal-theme/tools/build-theme.mjs <family>
//
// palette.json gives, per mode (dark/light): bg, fg, 16 seed colors (ANSI
// slots 0–15), a `highlightToward` color, and role slots for Fresh. The tool:
//   1. adjusts each seed's *lightness only* (hue/saturation kept) until it
//      reaches the contrast target on the background — lighter in dark mode,
//      darker in light mode (slot 0 in dark mode is a near-background shade
//      and is left alone);
//   2. picks the strongest selection shade (bg → highlightToward) that keeps
//      every text color >= 4.5:1 on it, and a hover shade halfway to it;
//   3. writes ghostty/<Name> Dark|Light and fresh/<family>-dark|light.json
//      (Fresh keys come from an existing theme, so every field is covered);
//   4. prints a contrast report.
// Contrast is WCAG 2 relative-luminance contrast; AA for text is 4.5:1.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const family = process.argv[2];
if (!family) {
  console.error('usage: build-theme.mjs <family>');
  process.exit(1);
}
const spec = JSON.parse(fs.readFileSync(path.join(ROOT, family, 'palette.json'), 'utf8'));

// ---------- color math ----------
const toRgb = (h) => [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16));
const toHex = (rgb) => '#' + rgb.map((v) => Math.round(Math.max(0, Math.min(255, v))).toString(16).padStart(2, '0')).join('');
function lum(h) {
  const [r, g, b] = toRgb(h).map((v) => {
    v /= 255;
    return v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4;
  });
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}
export function contrast(a, b) {
  const [x, y] = [lum(a), lum(b)].sort((p, q) => q - p);
  return (x + 0.05) / (y + 0.05);
}
function rgbToHsl([r, g, b]) {
  r /= 255; g /= 255; b /= 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b), l = (max + min) / 2;
  if (max === min) return [0, 0, l];
  const d = max - min, s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
  const h = max === r ? (g - b) / d + (g < b ? 6 : 0) : max === g ? (b - r) / d + 2 : (r - g) / d + 4;
  return [h / 6, s, l];
}
function hslToRgb([h, s, l]) {
  if (s === 0) return [l * 255, l * 255, l * 255];
  const q = l < 0.5 ? l * (1 + s) : l + s - l * s, p = 2 * l - q;
  const f = (t) => {
    t = (t + 1) % 1;
    if (t < 1 / 6) return p + (q - p) * 6 * t;
    if (t < 1 / 2) return q;
    if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6;
    return p;
  };
  return [f(h + 1 / 3) * 255, f(h) * 255, f(h - 1 / 3) * 255];
}
function tune(hex, bg, target, lighter) {
  let [h, s, l] = rgbToHsl(toRgb(hex));
  let out = hex;
  while (contrast(out, bg) < target && l > 0 && l < 1) {
    l = Math.max(0, Math.min(1, l + (lighter ? 0.004 : -0.004)));
    out = toHex(hslToRgb([h, s, l]));
  }
  return out;
}
const mix = (a, b, t) => toHex(toRgb(a).map((x, i) => x * t + toRgb(b)[i] * (1 - t)));

// ---------- build each mode ----------
const built = {};
for (const mode of ['dark', 'light']) {
  const m = spec[mode];
  const target = m.target ?? (mode === 'dark' ? 6.0 : 4.8);
  const pal = m.seed.map((c, i) => (mode === 'dark' && i === 0 ? c : tune(c, m.bg, target, mode === 'dark')));
  const texts = [m.fg, ...pal.filter((_, i) => !(mode === 'dark' && i === 0))];
  let t = m.highlightMax ?? 1;
  while (t > 0 && Math.min(...texts.map((c) => contrast(c, mix(m.highlightToward, m.bg, t)))) < 4.5) t -= 0.02;
  const sel = mix(m.highlightToward, m.bg, t);
  const hover = mix(m.highlightToward, m.bg, t * 0.45);
  built[mode] = { ...m, pal, sel, hover };

  const NAMES = ['black', 'red', 'green', 'yellow', 'blue', 'magenta', 'cyan', 'white', 'brBlack', 'brRed', 'brGreen', 'brYellow', 'brBlue', 'brMagenta', 'brCyan', 'brWhite'];
  console.log(`== ${spec.name} ${mode}: bg ${m.bg}, text ${contrast(m.fg, m.bg).toFixed(1)}:1, selection ${sel} (text ${contrast(m.fg, sel).toFixed(1)}:1, vs bg ${contrast(sel, m.bg).toFixed(2)})`);
  pal.forEach((c, i) =>
    console.log(`   ${String(i).padStart(2)} ${NAMES[i].padEnd(10)} ${m.seed[i]} -> ${c}  on bg ${contrast(c, m.bg).toFixed(1).padStart(4)}  on selection ${contrast(c, sel).toFixed(1).padStart(4)}`)
  );
}

// ---------- Ghostty ----------
const ghosttyDir = path.join(ROOT, family, 'ghostty');
fs.mkdirSync(ghosttyDir, { recursive: true });
for (const mode of ['dark', 'light']) {
  const b = built[mode];
  const title = `${spec.name} ${mode === 'dark' ? 'Dark' : 'Light'}`;
  const lines = [
    `# ${title} — ${spec.description}`,
    `# Generated by terminal-theme/tools/build-theme.mjs from ${family}/palette.json.`,
    `# Every text color is >= ${mode === 'dark' ? '6.0' : '4.8'}:1 on the background` + (mode === 'dark' ? '; color 0 is the near-background shade.' : '.'),
    ...b.pal.map((c, i) => `palette = ${i}=${c}`),
    `background = ${b.bg}`,
    `foreground = ${b.fg}`,
    `cursor-color = ${b.fg}`,
    `cursor-text = ${b.bg}`,
    `selection-background = ${b.sel}`,
    `selection-foreground = ${b.fg}`,
  ];
  fs.writeFileSync(path.join(ghosttyDir, title), lines.join('\n') + '\n');
}

// ---------- Fresh ----------
// Key list from an existing, complete theme; each key gets a color by role.
const template = JSON.parse(fs.readFileSync(path.join(ROOT, 'heather', 'fresh', 'heather-dark.json'), 'utf8'));
const freshDir = path.join(ROOT, family, 'fresh');
fs.mkdirSync(freshDir, { recursive: true });
const SEL_BG = ['selection_bg', 'prompt_selection_bg', 'popup_selection_bg', 'text_input_selection_bg', 'suggestion_selected_bg', 'menu_active_bg', 'menu_highlight_bg', 'settings_selected_bg', 'tab_drop_zone_bg'];
const HOVER_BG = ['current_line_bg', 'tab_hover_bg', 'menu_hover_bg', 'inline_code_bg', 'ruler_bg', 'blame_header_bg', 'tour_step_bg', 'status_palette_bg'];
const MUTED_FG = ['inactive_cursor', 'line_number_fg', 'whitespace_indicator_fg', 'indentation_guide_fg', 'menu_border_fg', 'menu_separator_fg', 'menu_disabled_fg', 'help_separator_fg', 'split_separator_fg', 'scrollbar_track_fg', 'scrollbar_thumb_fg', 'scrollbar_track_hover_fg', 'scrollbar_thumb_hover_fg', 'popup_border_fg', 'tab_inactive_fg', 'file_status_untracked_fg', 'status_separator_fg', 'tab_separator_fg'];

for (const mode of ['dark', 'light']) {
  const b = built[mode];
  const r = Object.fromEntries(Object.entries(spec.roles).map(([role, slot]) => [role, b.pal[slot]]));
  const T = {
    ...r, fg: b.fg, sel: b.sel, hover: b.hover,
    amberBg: mix(r.warning, b.bg, mode === 'dark' ? 0.28 : 0.22),
    redBg: mix(r.error, b.bg, mode === 'dark' ? 0.28 : 0.2),
    greenBg: mix(r.success, b.bg, mode === 'dark' ? 0.28 : 0.2),
  };
  const rgb = (h) => toRgb(h);
  const pick = (section, k) => {
    if (section === 'syntax') {
      return {
        keyword: { color: rgb(T.accent), modifier: ['bold'] }, string: T.code, comment: T.muted, function: T.link, type: T.warning,
        variable: 'Default', variable_builtin: T.constant, constant: T.constant, operator: 'Default',
        punctuation_bracket: T.muted, punctuation_delimiter: T.muted, escape: T.link,
      }[k];
    }
    if (section === 'search') return { match_bg: T.amberBg, match_fg: 'Default', label_bg: T.sel, label_fg: 'Default' }[k];
    if (section === 'diagnostic') {
      if (k.endsWith('_bg')) return 'Default';
      return { error_fg: T.error, warning_fg: T.warning, info_fg: T.link, hint_fg: T.muted }[k];
    }
    if (['bg', 'fg', 'cursor', 'terminal_bg', 'terminal_fg'].includes(k)) return 'Default';
    if (k.startsWith('bracket_rainbow_')) return [T.accent, T.warning, T.code, T.link, T.constant, T.extra][+k.at(-1) - 1];
    if (k.startsWith('indent_rainbow_')) return [T.extra, T.code, T.warning, T.constant, T.muted, T.link][+k.at(-1) - 1];
    if (k === 'bracket_match_fg') return T.accent;
    if (SEL_BG.includes(k)) return T.sel;
    if (HOVER_BG.includes(k)) return T.hover;
    if (['diff_add_bg', 'diff_add_highlight_bg'].includes(k)) return T.greenBg;
    if (['diff_remove_bg', 'diff_remove_highlight_bg', 'status_error_indicator_bg', 'status_error_indicator_hover_bg'].includes(k)) return T.redBg;
    if (['diff_modify_bg', 'status_lsp_actionable_bg', 'status_warning_indicator_bg', 'status_warning_indicator_hover_bg'].includes(k)) return T.amberBg;
    if (k.endsWith('_bg')) return 'Default';
    if (['tab_active_fg', 'split_separator_hover_fg', 'tab_drop_zone_border'].includes(k)) return T.accent;
    if (k === 'help_key_fg' || k === 'file_status_renamed_fg') return T.extra;
    if (['help_indicator_fg', 'tab_close_hover_fg', 'file_status_deleted_fg'].includes(k)) return T.error;
    if (k === 'file_status_added_fg') return T.success;
    if (k === 'file_status_modified_fg') return T.warning;
    if (k === 'file_status_conflicted_fg') return T.constant;
    if (MUTED_FG.includes(k)) return T.muted;
    if (k === 'whitespace_indicator_selected_fg') return T.fg;
    if (k.endsWith('_fg') || k.endsWith('_border')) return 'Default';
    if (k === 'selection_modifier') return [];
    return undefined;
  };
  const out = { name: `${family}-${mode}`, extends: `builtin://${mode}` };
  for (const section of ['editor', 'ui', 'search', 'diagnostic', 'syntax']) {
    out[section] = {};
    for (const k of Object.keys(template[section])) {
      const v = pick(section, k);
      if (v === undefined) throw new Error(`no rule for ${section}.${k}`);
      out[section][k] = typeof v === 'string' && v.startsWith('#') ? rgb(v) : v;
    }
  }
  fs.writeFileSync(path.join(freshDir, `${family}-${mode}.json`), JSON.stringify(out, null, 2) + '\n');

  const textColors = [T.fg, T.muted, T.accent, T.error, T.warning, T.success, T.code, T.link, T.constant, T.extra];
  const worst = Math.min(...textColors.flatMap((c) => [b.bg, T.hover, T.sel].map((bg) => contrast(c, bg))));
  console.log(`   Fresh ${mode}: worst text on bg/hover/selection ${worst.toFixed(2)}:1; text on search/error/diff fills ${Math.min(...[T.amberBg, T.redBg, T.greenBg].map((f) => contrast(T.fg, f))).toFixed(1)}:1+`);
}
console.log(`Wrote ${family}/ghostty and ${family}/fresh.`);
